title: 学而实习之
description: PHP GO NoSQL 学 而 实习 之

theme: null

# 评论功能
gitalk:
  clientID: 'bd9542005fed5648ca99'
  clientSecret: '3a211de3b3cb3c4318393cd70d3901bec8faa855'
  repo: 'wxyClark.github.io'
  owner: 'wxyClark'
  admin: 'wxyClark'
  distractionFreeMode: true

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
