title: 学而实习之
description: PHP GO NoSQL 学 而 实习 之

theme: jekyll-rtd-theme  

# 评论功能
gitalk:
  clientID: 'bd9542005fed5648ca99'
  clientSecret: '2e924f036f336bbd5289325bd60d24dde44eac61'
  repo: 'wxyClark.github.io'
  owner: 'wxyClark'
  admin: 'wxyClark'
  distractionFreeMode: true

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
